### ISSUE TITLE
Help wanted, Error linking clang with ScaffCC

### ISSUE THREAD

**Issue by marsscout22** [ScaffCC/ScaffCC#8]
I followed these steps https://github.com/ScaffCC/ScaffCC#installation and I got this error, any help?
@xiangzhai 

[ 88%] Linking CXX executable ../../../../bin/clang
../../../../lib/libclangSerialization.a(ASTReaderStmt.cpp.o): In function `clang::ASTReader::ReadStmtFromStream(clan          g::serialization::ModuleFile&)':
ASTReaderStmt.cpp:(.text._ZN5clang9ASTReader18ReadStmtFromStreamERNS_13serialization10ModuleFileE+0x25d6): undefined           reference to `clang::ObjCAtTryStmt::CreateEmpty(clang::ASTContext const&, unsigned int, bool)'
../../../../lib/libclangSema.a(SemaStmt.cpp.o): In function `clang::Sema::ActOnObjCForCollectionStmt(clang::SourceLo          cation, clang::Stmt*, clang::Expr*, clang::SourceLocation)':
/root/ScaffCC/llvm/tools/clang/lib/Sema/SemaStmt.cpp:1949: undefined reference to `clang::ObjCForCollectionStmt::Obj          CForCollectionStmt(clang::Stmt*, clang::Expr*, clang::Stmt*, clang::SourceLocation, clang::SourceLocation)'
../../../../lib/libclangSema.a(SemaStmt.cpp.o): In function `clang::Sema::ActOnObjCAtTryStmt(clang::SourceLocation,           clang::Stmt*, llvm::MutableArrayRef<clang::Stmt*>, clang::Stmt*)':
/root/ScaffCC/llvm/tools/clang/lib/Sema/SemaStmt.cpp:3608: undefined reference to `clang::ObjCAtTryStmt::Create(clan          g::ASTContext const&, clang::SourceLocation, clang::Stmt*, clang::Stmt**, unsigned int, clang::Stmt*)'
../../../../lib/libclangAST.a(ASTImporter.cpp.o): In function `clang::ASTNodeImporter::VisitObjCForCollectionStmt(cl          ang::ObjCForCollectionStmt*)':
ASTImporter.cpp:(.text._ZN5clang15ASTNodeImporter26VisitObjCForCollectionStmtEPNS_21ObjCForCollectionStmtE+0xda): un          defined reference to `clang::ObjCForCollectionStmt::ObjCForCollectionStmt(clang::Stmt*, clang::Expr*, clang::Stmt*,           clang::SourceLocation, clang::SourceLocation)'
../../../../lib/libclangAST.a(ASTImporter.cpp.o): In function `clang::ASTNodeImporter::VisitObjCAtTryStmt(clang::Obj          CAtTryStmt*)':
ASTImporter.cpp:(.text._ZN5clang15ASTNodeImporter18VisitObjCAtTryStmtEPNS_13ObjCAtTryStmtE+0x269): undefined referen          ce to `clang::ObjCAtTryStmt::Create(clang::ASTContext const&, clang::SourceLocation, clang::Stmt*, clang::Stmt**, un          signed int, clang::Stmt*)'
../../../../lib/libclangAST.a(Stmt.cpp.o): In function `clang::Stmt::getSourceRange() const':
Stmt.cpp:(.text._ZNK5clang4Stmt14getSourceRangeEv+0x2df): undefined reference to `clang::ObjCAtTryStmt::getLocEnd()           const'
../../../../lib/libclangAST.a(Stmt.cpp.o): In function `clang::Stmt::getLocEnd() const':
Stmt.cpp:(.text._ZNK5clang4Stmt9getLocEndEv+0x460): undefined reference to `clang::ObjCAtTryStmt::getLocEnd() const'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [tools/clang/tools/driver/CMakeFiles/clang.dir/build.make:303: bin/clang-7.0] Error 1
make[3]: Leaving directory '/root/ScaffCC/build'
make[2]: *** [CMakeFiles/Makefile2:24711: tools/clang/tools/driver/CMakeFiles/clang.dir/all] Error 2
make[2]: Leaving directory '/root/ScaffCC/build'
make[1]: *** [Makefile:152: all] Error 2
make[1]: Leaving directory '/root/ScaffCC/build'
make: *** [Makefile:114: Clang] Error 2

**Comment by xiangzhai** [comment]
Hi @marsscout22 

Please git pull scaff-llvm and scaff-clang,  I merged with upstream,  then rebuilt with clang-3.9.1 on Linux 4.13.16-100.fc25.x86_64:
<pre>
$ make DISABLE_STATIC=1
...
[100%] Built target benchmark
make[3]: Entering directory '/data/project/ScaffCC/ScaffCC/build'
make[3]: Leaving directory '/data/project/ScaffCC/ScaffCC/build'
[100%] Built target benchmark_main
make[2]: Leaving directory '/data/project/ScaffCC/ScaffCC/build'
make[1]: Leaving directory '/data/project/ScaffCC/ScaffCC/build'
</pre>

Simulate:
<pre>
$ ./scaffold.sh -fkR Algorithms/Cat_State/cat_state.n04.scaffold
[Scaffold.makefile] Compiling cat_state.n04_merged.scaffold ...
clang version 8.0.0 (git@github.com:llvm-mirror/clang.git 40523c2c53b1beadc74e844bce8c39f485e51ee3) (git@github.com:llvm-mirror/llvm.git 722c0bae42af19309cd4b9ab4369cfd7bd0895cd)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /data/project/ScaffCC/ScaffCC/./build/bin
Found candidate GCC installation: /usr/lib/gcc/i686-redhat-linux/6.4.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/6.4.1
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/6.4.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
 "/data/project/ScaffCC/ScaffCC/build/bin/clang-8" -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm -disable-free -main-file-name cat_state.n04_merged.scaffold -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file /data/project/ScaffCC/ScaffCC/cat_state.n04.gcno -resource-dir /data/project/ScaffCC/ScaffCC/build/lib/clang/8.0.0 -I Algorithms/Cat_State/ -internal-isystem /usr/local/include -internal-isystem /data/project/ScaffCC/ScaffCC/build/lib/clang/8.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /data/project/ScaffCC/ScaffCC -ferror-limit 19 -fmessage-length 112 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -disable-O0-optnone -o cat_state.n04.ll -x c cat_state.n04_merged.scaffold -faddrsig
clang -cc1 version 8.0.0 based upon LLVM 8.0.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 Algorithms/Cat_State
 /usr/local/include
 /data/project/ScaffCC/ScaffCC/build/lib/clang/8.0.0/include
 /usr/include
End of search list.
[Scaffold.makefile] Transforming cbits ...
[Scaffold.makefile] O1 optimizations ...
[Scaffold.makefile] Unrolling Loops (1) ...
[Scaffold.makefile] Cloning Functions (1) ...
Functions Cloned: 1
[Scaffold.makefile] Dead Argument Elimination (1) ...
[Scaffold.makefile] Unrolling Loops (2) ...
[Scaffold.makefile] Cloning Functions (2) ...
Functions Cloned: 0
[Scaffold.makefile] Dead Argument Elimination (2) ...
[Scaffold.makefile] Unrolling Loops (3) ...
[Scaffold.makefile] Cloning Functions (3) ...
Functions Cloned: 0
[Scaffold.makefile] Dead Argument Elimination (3) ...
[Scaffold.makefile] Internalizing and Removing Unused Functions ...
[Scaffold.makefile] Toffoli Decomposition ...
[Scaffold.makefile] Inserting Reverse Functions...
[Scaffold.makefile] Flattening modules ...
[Scaffold.makefile] Flat QASM written to cat_state.n04.qasmf ...

$ ./cat_state.n04_qasm
H bits0
CNOT bits1,bits0
CNOT bits2,bits1
CNOT bits3,bits2
</pre>

**Comment by marsscout22** [comment]
It still did not work and It worked on Ubuntu system, thank you for helping

**Comment by xiangzhai** [comment]
> It still did not work

Mac? sorry, I only have Linux :)
